/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_PROTOBUF_TELEMETRY_PB_H_INCLUDED
#define PB_PROTOBUF_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Telemetry_ENV {
    float temperature;
    float humidity;
    float pressure;
    float light;
} Telemetry_ENV;

typedef struct _Telemetry {
    bool has_env;
    Telemetry_ENV env;
} Telemetry;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Telemetry_init_default                   {false, Telemetry_ENV_init_default}
#define Telemetry_ENV_init_default               {0, 0, 0, 0}
#define Telemetry_init_zero                      {false, Telemetry_ENV_init_zero}
#define Telemetry_ENV_init_zero                  {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Telemetry_ENV_temperature_tag            1
#define Telemetry_ENV_humidity_tag               2
#define Telemetry_ENV_pressure_tag               3
#define Telemetry_ENV_light_tag                  4
#define Telemetry_env_tag                        1

/* Struct field encoding specification for nanopb */
#define Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  env,               1)
#define Telemetry_CALLBACK NULL
#define Telemetry_DEFAULT NULL
#define Telemetry_env_MSGTYPE Telemetry_ENV

#define Telemetry_ENV_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    light,             4)
#define Telemetry_ENV_CALLBACK NULL
#define Telemetry_ENV_DEFAULT NULL

extern const pb_msgdesc_t Telemetry_msg;
extern const pb_msgdesc_t Telemetry_ENV_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Telemetry_fields &Telemetry_msg
#define Telemetry_ENV_fields &Telemetry_ENV_msg

/* Maximum encoded size of messages (where known) */
#define PROTOBUF_TELEMETRY_PB_H_MAX_SIZE         Telemetry_size
#define Telemetry_ENV_size                       20
#define Telemetry_size                           22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
