# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpacket.proto\"@\n\x06Packet\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x1d\n\ttelemetry\x18\x02 \x01(\x0b\x32\n.Telemetry\"9\n\x06Header\x12\r\n\x05index\x18\x01 \x01(\r\x12\x0c\n\x04time\x18\x02 \x01(\x04\x12\x12\n\nsession_id\x18\x03 \x01(\x04\"\xab\x04\n\tTelemetry\x12\x1b\n\x03\x65nv\x18\x01 \x01(\x0b\x32\x0e.Telemetry.ENV\x12\x1b\n\x03gps\x18\x02 \x01(\x0b\x32\x0e.Telemetry.GPS\x12!\n\x06\x62mi160\x18\x03 \x01(\x0b\x32\x11.Telemetry.BMI160\x12\x1f\n\x05radio\x18\x04 \x01(\x0b\x32\x10.Telemetry.Radio\x12\x1b\n\x03gas\x18\x05 \x01(\x0b\x32\x0e.Telemetry.Gas\x1aM\n\x03\x45NV\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\x12\x10\n\x08pressure\x18\x03 \x01(\x02\x12\r\n\x05light\x18\x04 \x01(\x02\x1as\n\x03GPS\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x02\x12\r\n\x05speed\x18\x04 \x01(\x02\x12\x12\n\nsatellites\x18\x05 \x01(\r\x12\x12\n\nepoch_time\x18\x06 \x01(\x04\x1a_\n\x06\x42MI160\x12\x0c\n\x04\x61\x63\x63X\x18\x01 \x01(\x02\x12\x0c\n\x04\x61\x63\x63Y\x18\x02 \x01(\x02\x12\x0c\n\x04\x61\x63\x63Z\x18\x03 \x01(\x02\x12\r\n\x05gyroX\x18\x04 \x01(\x02\x12\r\n\x05gyroY\x18\x05 \x01(\x02\x12\r\n\x05gyroZ\x18\x06 \x01(\x02\x1a\"\n\x05Radio\x12\x0c\n\x04RSSI\x18\x01 \x01(\x05\x12\x0b\n\x03SNR\x18\x02 \x01(\x02\x1a:\n\x03Gas\x12\x0b\n\x03\x63o2\x18\x01 \x01(\x02\x12\r\n\x05metan\x18\x02 \x01(\x02\x12\x17\n\x0fmetan_threshold\x18\x03 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PACKET']._serialized_start=16
  _globals['_PACKET']._serialized_end=80
  _globals['_HEADER']._serialized_start=82
  _globals['_HEADER']._serialized_end=139
  _globals['_TELEMETRY']._serialized_start=142
  _globals['_TELEMETRY']._serialized_end=697
  _globals['_TELEMETRY_ENV']._serialized_start=310
  _globals['_TELEMETRY_ENV']._serialized_end=387
  _globals['_TELEMETRY_GPS']._serialized_start=389
  _globals['_TELEMETRY_GPS']._serialized_end=504
  _globals['_TELEMETRY_BMI160']._serialized_start=506
  _globals['_TELEMETRY_BMI160']._serialized_end=601
  _globals['_TELEMETRY_RADIO']._serialized_start=603
  _globals['_TELEMETRY_RADIO']._serialized_end=637
  _globals['_TELEMETRY_GAS']._serialized_start=639
  _globals['_TELEMETRY_GAS']._serialized_end=697
# @@protoc_insertion_point(module_scope)
