# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpacket.proto\"@\n\x06Packet\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x1d\n\ttelemetry\x18\x02 \x01(\x0b\x32\n.Telemetry\"%\n\x06Header\x12\r\n\x05index\x18\x01 \x01(\r\x12\x0c\n\x04time\x18\x02 \x01(\x04\"w\n\tTelemetry\x12\x1b\n\x03\x65nv\x18\x01 \x01(\x0b\x32\x0e.Telemetry.ENV\x1aM\n\x03\x45NV\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\x12\x10\n\x08pressure\x18\x03 \x01(\x02\x12\r\n\x05light\x18\x04 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PACKET']._serialized_start=16
  _globals['_PACKET']._serialized_end=80
  _globals['_HEADER']._serialized_start=82
  _globals['_HEADER']._serialized_end=119
  _globals['_TELEMETRY']._serialized_start=121
  _globals['_TELEMETRY']._serialized_end=240
  _globals['_TELEMETRY_ENV']._serialized_start=163
  _globals['_TELEMETRY_ENV']._serialized_end=240
# @@protoc_insertion_point(module_scope)
